services:
    phpbb.boardannouncements.listener:
        class: phpbb\boardannouncements\event\listener
        arguments:
            - '@phpbb.boardannouncements.manager'
            - '@config'
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    phpbb.boardannouncements.controller:
        class: phpbb\boardannouncements\controller\controller
        arguments:
            - '@phpbb.boardannouncements.manager'
            - '@request'
            - '@user'

    phpbb.boardannouncements.manager:
        class: phpbb\boardannouncements\manager\manager
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%board_announcements'
            - '%core.table_prefix%board_announcements_track'

    phpbb.boardannouncements.acp.controller:
        class: phpbb\boardannouncements\controller\acp_controller
        arguments:
            - '@phpbb.boardannouncements.manager'
            - '@controller.helper'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
